name: 4 — Allure Report + GitHub Pages

on:
  workflow_run:
    workflows: ["2 — Regression Tests"]
    types: [ completed ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  allure-report:
    name: Publish Allure to GitHub Pages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Regression Allure Results
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: regression.yml
          name: regression-allure-results
          path: target/allure-results

      - name: Get Allure History
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history